### PR TITLE
initial import from ryanj (https://github.com/ryanj/origin-s2i-nodejs)

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@ryanj @jawnsy ptal

**Comment by jawnsy** [comment]
LGTM, glad you were able to preserve all the history!

I understand the repo name `s2i-nodejs-community` is intended to differentiate with the SCL version; is this a general pattern that we should apply to the rest of the community repositories?

**Comment by bparees** [comment]
>  is this a general pattern that we should apply to the rest of the community repositories?

@jawnsy i don't think so. the whole openshift-s2i repo is community content, so i don't think we need to lengthen people's repo names unnecessarily, except in cases where there might be confusion.

**Comment by jawnsy** [comment]
@bparees Okay, agreed. We can always rename repositories later if they become ambiguous (for example, if we "promote" one of the community images to an SCL-supported version)

**Pull request merged**
